# Generated by Django 5.0.3 on 2024-04-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GptQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('초등학생', '초등학생'), ('중학생', '중학생'), ('고등학생', '고등학생'), ('원어민', '원어민'), ('토플', '토플')], max_length=30)),
                ('orderNum', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
