# Generated by Django 5.0.3 on 2024-04-18 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gptquestionanswer',
            name='orderNum',
        ),
    ]
