# Generated by Django 5.0.4 on 2024-04-21 08:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='gptanswer',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
