# Generated by Django 5.0.3 on 2024-04-08 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedbacks', '0001_initial'),
        ('quizs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizs.quiz'),
        ),
    ]
